apiVersion: v1
kind: Namespace
metadata:
  name: twenty-crm

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: twenty-crm-config
  namespace: twenty-crm
data:
  DATABASE_URL: "mysql://mysqluser:mysqlpassword@mysql/twentycrm"

---
apiVersion: v1
kind: Secret
metadata:
  name: twenty-crm-secret
  namespace: twenty-crm
type: Opaque
data:
  mysql-root-password: c3VwZXJzZWNyZXRwYXNz  # supersecretpass (base64 encoded)
  mysql-password: bXlzcWxxcGFzc3dvcmQ=      # mysqlpassword (base64 encoded)

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: twenty-crm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: twenty-crm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: twenty-crm
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twenty-crm-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: "twentycrm"
            - name: MYSQL_USER
              value: "mysqluser"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twenty-crm-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: twenty-crm
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twenty-crm
  namespace: twenty-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twenty-crm
  template:
    metadata:
      labels:
        app: twenty-crm
    spec:
      containers:
        - image: twenty-crm:latest
          name: twenty-crm
          envFrom:
            - configMapRef:
                name: twenty-crm-config
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: twenty-crm-storage
              mountPath: /var/lib/twenty-crm
      volumes:
        - name: twenty-crm-storage
          persistentVolumeClaim:
            claimName: twenty-crm-pvc

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: twenty-crm-pv
  namespace: twenty-crm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/twenty-crm"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twenty-crm-pvc
  namespace: twenty-crm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: twenty-crm
  namespace: twenty-crm
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: twenty-crm
