# Persistent Volume Claim for MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        command: ["mysqld"]
        args: ["--max_allowed_packet=16777216", "--wait_timeout=300", "--net_read_timeout=300"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: civicrm
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: civicrm-db-secret
              key: db_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: civicrm-db-secret
              key: db_password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306

---
# Secret for Database Credentials
apiVersion: v1
kind: Secret
metadata:
  name: civicrm-db-secret
  namespace: default
type: Opaque
data:
  db_user: cGl1c2Vy # base64 encoded value of 'piuser'
  db_password: cGlwYXNz # base64 encoded value of 'pipass'
  db_name: Y2l2aWNybQ== # base64 encoded value of 'civicrm'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: default
data:
  my.cnf: |
    [mysqld]
    max_allowed_packet=128M
